/// INPUT FIELD
export const CHANGE_SEARCH_FIELD= "CHANGE_SEARCH_FIELD";
///ROBOTS API REQUEST
export const REQUEST_ROBOTS_PENDING= "REQUEST_ROBOTS_PENDING";
export const REQUEST_ROBOTS_FAILED= "REQUEST_ROBOTS_FAILED";
export const REQUEST_ROBOTS_SUCCESS= "REQUEST_ROBOTS_SUCCESS";